apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  # ConnectionStrings__Postgres: echo -n '<value>' | base64
  ConnectionStrings__Postgres: ""
  # ConnectionStrings__Redis: echo -n '<value>' | base64
  ConnectionStrings__Redis: ""
  # ConnectionStrings__SqlServer: echo -n '<value>' | base64
  ConnectionStrings__SqlServer: ""
  # Jwt__Key: echo -n '<RSA private key PEM>' | base64
  Jwt__Key: ""
  # Stripe__SecretKey: echo -n 'sk_live_...' | base64
  Stripe__SecretKey: ""
  # Stripe__PublishableKey: echo -n 'pk_live_...' | base64
  Stripe__PublishableKey: ""
  # Stripe__WebhookSigningSecret: echo -n 'whsec_...' | base64
  Stripe__WebhookSigningSecret: ""
  # OAuth__Clients__0__ClientSecret: echo -n '<value>' | base64
  OAuth__Clients__0__ClientSecret: ""
  # OAuth__Clients__1__ClientSecret: echo -n '<value>' | base64
  OAuth__Clients__1__ClientSecret: ""
