apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: ecommerce-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ConnectionStrings__Postgres
      remoteRef:
        key: ecommerce/prod/db-password
        version: AWSCURRENT
    - secretKey: ConnectionStrings__Redis
      remoteRef:
        key: ecommerce/prod/redis-password
        version: AWSCURRENT
    - secretKey: Jwt__Key
      remoteRef:
        key: ecommerce/prod/jwt-key-pem
        version: AWSCURRENT
    - secretKey: Stripe__SecretKey
      remoteRef:
        key: ecommerce/prod/stripe-secret-key
        version: AWSCURRENT
    - secretKey: Stripe__PublishableKey
      remoteRef:
        key: ecommerce/prod/stripe-publishable-key
        version: AWSCURRENT
    - secretKey: Stripe__WebhookSigningSecret
      remoteRef:
        key: ecommerce/prod/stripe-webhook-secret
        version: AWSCURRENT
    - secretKey: OAuth__Clients__0__ClientSecret
      remoteRef:
        key: ecommerce/prod/oauth-google-secret
        version: AWSCURRENT
    - secretKey: OAuth__Clients__1__ClientSecret
      remoteRef:
        key: ecommerce/prod/oauth-partner-secret
        version: AWSCURRENT
